# Generated by Django 4.1.4 on 2022-12-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, max_length=5),
        ),
    ]
